### ISSUE TITLE
Я сделала домашнее задание.

### ISSUE THREAD

**Issue by weti369** [MIEE-ACS/domashnee-zadanie-no3-weti369#1]

**Comment by d-makarenko** [comment]
> Я сделала
Ясно.

Над интерфейсом надо было немного поработать, я сходу даже подумал, что все работает неправильно из-за того, что текст не вместился.

3/4

**Comment by weti369** [comment]
Суббота, 21 октября 2017, 23:07 +03:00 от d-makarenko <notifications@github.com>:
>>Я сделала
>>Ясно.
>Над интерфейсом надо было немного поработать, я сходу даже подумал, что все работает неправильно из-за того, что текст не вместился.
>3/4
>—
>You are receiving this because you authored the thread.
>Reply to this email directly,  view it on GitHub , or  mute the thread .

Клава зависла не заметил

**Comment by weti369** [comment]
Суббота, 21 октября 2017, 23:07 +03:00 от d-makarenko <notifications@github.com>:
